philo_group/urls.py
from django.urls import path
from .views import AboutView, FaqView, Page404View, PostView, TagPostsView
from django.views.generic import TemplateView

app_name = 'philo_group'
urlpatterns = [

    path('about/', AboutView.as_view(), name='about'),
    path('', PostView.as_view(), name='sessions'),
    path('tag/<slug:tag_slug>/', TagPostsView.as_view(), name='tag_posts'),
    path('faq/', FaqView.as_view(), name='faq'),
    path('404/', Page404View.as_view(template_name='404.html'), name='404')

]

philosophy_site/urls.py
from django.contrib import admin
from django.urls import include, path
from philo_group import views as philoViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('philo_group.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

philo_group/models.py
from django.db import models
from django.utils import timezone
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
                     .filter(status=Post.Status.PUBLISHED)


class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)

    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    def __str__(self):
        return self.title


class Session(models.Model):

    title = models.CharField(max_length=250)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-publish']

    def __str__(self):
        return self.title


class PostsInSession(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    class SessionManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset()\
                     .filter(status=PostsInSession.Session)

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)

    
    objects = models.Manager()
    published = PublishedManager()

    def __str__(self):
        return str(self.session)


class SessionEventDate(models.Model):
    event_date = models.CharField(max_length=250)

philo_group/views.py
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, TemplateView

from taggit.models import Tag

from .models import Session, PostsInSession, SessionEventDate


class PostView(ListView):

    queryset = Session.objects.prefetch_related('postsinsession_set').all()
    context_object_name = 'sessions'
    template_name = 'sessions.html'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tags = Tag.objects.order_by('name')
        sessiondate = SessionEventDate.objects.filter(id=1)
        paginator = Paginator(self.queryset, self.paginate_by)
        page = self.request.GET.get('page')
        sessions = paginator.get_page(page)
        context['sessions'] = sessions
        context['tags'] = tags
        context['sessiondate'] = sessiondate
        return context


class TagPostsView(ListView):

    template_name = 'tag_posts.html'
    paginate_by = 5

    def get_queryset(self):
        tag_slug = self.get_tag_slug()
        posts = PostsInSession.objects.filter(post__tags__slug=tag_slug)
        return posts

    def get_tag_slug(self):
        return self.kwargs['tag_slug']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tag_slug = self.get_tag_slug()
        tag = get_object_or_404(Tag, slug=tag_slug)
        paginator = Paginator(self.get_queryset(), self.paginate_by)
        page = self.request.GET.get('page')
        paginated_posts = paginator.get_page(page)
        context['tag'] = tag
        context['posts'] = paginated_posts
        return context


class AboutView(TemplateView):
    template_name = 'about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        sessiondate = SessionEventDate.objects.filter(id=1)
        context['sessiondate'] = sessiondate
        return context


class FaqView(TemplateView):
    template_name = 'faq.html'


class Page404View (TemplateView):
    template_name = '404.html'

philo_group/templates/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container">
    <br>

    <div class="row">
        <div class="col-lg-6">
            <div class="jumbotron">
                <h1 class="display-4">Insert Title</h1>
                <i class="lead">Thought provoking quote</i>
                <p>- Old Person </p>
                <hr class="my-4">
                <h5>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </h5>
            </div>
        </div>
        <div class="col-lg-6">
            <img src="{% static 'images/busts.jpg' %}" class="img-fluid rounded opacity-light">
        </div>
    </div>

    <br>

    <div class="row">
        <br>
        <hr class="my-4"/>
        <hr class="my-4"/>
    </div>


    <div class="row">
        <div class="col-md-4">
            <h2>Section 1</h2>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                Ut enim ad minim veniam, quis nostrud exercitation ullamco
                laboris nisi ut aliquip ex ea commodo consequat.
        </div>

        <div class="col-md-4">
            <h2>Section 2</h2>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
        </div>

        <div class="col-md-4">
            <h2>Section 3</h2>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
        </div>
    </div>


    <div class="row">
        <br>
        <hr class="my-4"/>
        <hr class="my-4"/>
    </div>


    <div class="row">
        <div class="col-md-4">
            <h2 id="location">Location</h2>
            <p>
                Place Name, <br>
                100 Address Road, <br>
                Town, <br>
                City, <br>
                XX10 1AA
            </p>
        </div>

        <div class="col-md-4">
            <h2 id="contact">Sessions</h2>
            <p>
                Sessions Happen <br>
                Session start time: <b> XX:XX – XX:XX </b> <br>
                {% for date in sessiondate %}
                next session: <b>{{date.event_date}}</b>
                {% endfor %}
            </p>
        </div>

        <div class="col-md-4">
            <h2 id="contact">Contact</h2>
            <p>PHILOSOPHYEMAIL@EMAIL.COM</p>
        </div>

    </div>

</div>

{% include "footer.html" %}

{% endblock %}

philo_group/templates/base.html
<!doctype html>
<html lang="en">
  {% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/static/css/custom.css">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/philo-logo-cropped.png' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <title>Philosophy Group</title>
  </head>

  <body>
    <br>
    <nav class="full-width-navbar navbar navbar-expand-lg navbar-dark">
      <div class="container-sm">
        <img src="/static/images/philo-logo-cropped.png" width="30" height="30" alt="">
        <a class="navbar-brand" href="{% url 'philo_group:sessions' %}">Philosophy Group</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'philo_group:sessions' %}">Sessions</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'philo_group:about' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'philo_group:faq' %}">FAQs</a>
            </li>
          </ul>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'admin:index' %}">Login</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    
      {% block content %}
      {% endblock %}

  </body>
</html>

philo_group/templates/faq.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <br>

    <h2> FAQS </h2>

    <hr class="my-4"/>

    <div class="accordion" id="faqAccordion">

        <div class="accordion-item">
            <h2 class="accordion-header" id="faqHeading1">
              <button class="accordion-button collapsed"
                      type="button"
                      data-bs-toggle="collapse" data-bs-target="#faqCollapse1"
                      aria-expanded="false" aria-controls="faqCollapse1">
                Question 1
              </button>
            </h2>
            <div id="faqCollapse1" class="accordion-collapse collapse"
                 aria-labelledby="faqHeading1" data-bs-parent="#faqAccordion">
              <div class="accordion-body">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                do eiusmod tempor incididunt ut labore et dolore magna aliqua.
              </div>
            </div>
          </div>

        <div class="accordion-item">
          <h2 class="accordion-header" id="faqHeading2">
            <button class="accordion-button collapsed" type="button"
                    data-bs-toggle="collapse" data-bs-target="#faqCollapse2"
                    aria-expanded="false" aria-controls="faqCollapse2">
              Question 2
            </button>
          </h2>
          <div id="faqCollapse2" class="accordion-collapse collapse"
               aria-labelledby="faqHeading2" data-bs-parent="#faqAccordion">
            <div class="accordion-body">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
              do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </div>
          </div>
        </div>

        <div class="accordion-item">
          <h2 class="accordion-header" id="faqHeading3">
            <button class="accordion-button collapsed" type="button"
                    data-bs-toggle="collapse" data-bs-target="#faqCollapse3"
                    aria-expanded="false" aria-controls="faqCollapse3">
              Question 3
            </button>
          </h2>
          <div id="faqCollapse3" class="accordion-collapse collapse" 
               aria-labelledby="faqHeading3" data-bs-parent="#faqAccordion">
            <div class="accordion-body">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
              do eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </div>
          </div>
        </div>

      </div>
      

</div>


  

{% include "footer.html" %}

{% endblock %}

philo_group/templates/footer.html
    <footer
      class="footer-container text-center text-white"
      style="background-color: #5c635f"
    >

      <div class="footer-content">
        <section class="mt-5">
          <div class="row text-center d-flex justify-content-center pt-3">
            
            <div class="col-md-2-footer">
              <h6 class="text-uppercase font-weight-bold">
                <a
                  href="{% url 'philo_group:about' %}"
                  class="text-white">About
                </a>
              </h6>
            </div>

            <div class="col-md-2-footer">
              <h6 class="text-uppercase font-weight-bold">
                <a
                  href="{% url 'philo_group:sessions' %}"
                  class="text-white"> sessions
                </a>
              </h6>
            </div>

            <div class="col-md-2-footer">
              <h6 class="text-uppercase font-weight-bold">
                <a
                  href="{% url 'philo_group:about' %}#location"
                  class="text-white">Location
                </a>
              </h6>
            </div>

            <div class="col-md-2-footer">
              <h6 class="text-uppercase font-weight-bold">
                <a
                href="{% url 'philo_group:about' %}#contact"
                class="text-white">Contact
                </a>
              </h6>
            </div>

            <div class="col-md-2-footer">
              <h6 class="text-uppercase font-weight-bold">
                <a
                href="{% url 'philo_group:faq' %}"
                class="text-white">FAQs
                </a>
              </h6>
            </div>
            
          </div>
        </section>

        <hr class="my-3" />
      
      <div
           class="text-center p-3"
           style="background-color: rgba(0, 0, 0, 0.2)"
           >
           <img src="/static/images/philo-logo-cropped.png" width="30" height="30" alt="">
        Philosophy Group
      </div>

    </div>
    
  </footer>
  <br>

philo_group/templates/sessions.html
{% extends "base.html" %}
{% load markdownify %}

{% block content %}
<br>

<div class="container">

  
  
  <!--alert bar -->
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <div class="row"> 
      <div class="col-md-10">
      {% for date in sessiondate %}
        <strong>Next Session:</strong>
        {{ date.event_date }} @ VENUE ADDRESS
      </div>
      <div class="col">
        <a
          href="{% url 'philo_group:about' %}#location"
          class="justify-content-end"
        >
          more info
        </a>
    </div>
  </div>
    
    {% endfor %}
    <button
      type="button"
      class="btn-close"
      data-bs-dismiss="alert"
      aria-label="Close">
    </button>
  </div>

  <!--cards -->
  <div class="row">

    <div class="col">
      {% for session in sessions %}
        <div class="card m-3">
          <div class="card-header text-center">
            {{ session.title }}
          </div>

          <div class="card-body">
            {% for post in session.postsinsession_set.all %}
              <div class="accordion" id="accordiansession">
                <div class="accordion-item">
                  <h2 class="accordion-header" id="heading{{ post.post.id }}">
                    <button
                      class="accordion-button collapsed"
                      type="button" data-bs-toggle="collapse"
                      data-bs-target="#collapse{{ post.post.id }}"
                      aria-expanded="false"
                      aria-controls="collapse{{ post.post.id }}">
                      {{ post.post.title }}
                    </button>
                  </h2>
                  <div
                    id="collapse{{ post.post.id }}"
                    class="accordion-collapse collapse"
                    aria-labelledby="heading{{ post.post.id }}"
                    data-bs-parent="#accordiansession"
                  >
                    <div class="accordion-body">
                      <p>{{ post.post.body | markdownify }} </p>
                      <p class="text-end fs-6 fw-lighter fst-italic">Tags:
                        {% for tag in post.post.tags.all %}
                          <a
                            href="{% url 'philo_group:tag_posts' tag.slug %}">{{ tag }}</a>{% if not forloop.last %},{% endif %}
                        {% endfor %}
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
      {% endfor %}
    </div>

    <div class="col-4"> 
      <div class="card border-light mb-3" style="max-width: 18rem;">
        <div class="card-header">Tags</div>
        <div class="card-body">
          {% for tag in tags %}
            <a href="{% url 'philo_group:tag_posts' tag.slug %}">{{ tag }}</a>{% if not forloop.last %}, {% endif %}
          {% endfor %}
        </div>
      </div>

      <div class="card border-light mb-3" style="max-width: 18rem;">
        <div class="card-header">About these Sessions </div>
        <div class="card-body">
          <p class="card-text">
            The sessions listed here are a summary and notes of the subjects
            discussed in each session
          </p>
        </div>
      </div>

    </div>

  
  </div>

  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      {% if sessions.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ sessions.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% endif %}
      
      {% for num in sessions.paginator.page_range %}
        {% if sessions.number == num %}
          <li class="page-item active" aria-current="page">
            <span class="page-link">{{ num }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
          </li>
        {% endif %}
      {% endfor %}
      
      {% if sessions.has_next %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{ sessions.next_page_number }}"
            aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
  

</div>
{% include "footer.html" %}
{% endblock %}

philo_group/templates/tag_posts.html
{% extends "base.html" %}
{% load markdownify %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col">
      <br>
      {% if tag %}
        <h2>Tag: {{ tag.name }}</h2>
      {% endif %}
      <hr>
      {% for post in posts %}
      <div class="card m-3 text-center">
  
        <div class="card-header">
          {{ post.post.title }}
        </div>
  
        <div class="card-body">
          {{ post.post.body|markdownify }}
        </div>
  
      </div>
      {% endfor %}
      <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
          {% if posts.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ posts.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
          {% endif %}
          
          {% for num in posts.paginator.page_range %}
            {% if posts.number == num %}
              <li class="page-item active" aria-current="page">
                <span class="page-link">{{ num }}</span>
              </li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
              </li>
            {% endif %}
          {% endfor %}
          
          {% if posts.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ posts.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </div>
</div>

{% include "footer.html" %}

{% endblock %}